### PR TITLE
Adding script to clear down Postgres WAL archive

### PR DESCRIPTION
**Pull request by RobHooper**
Adding script to clear down WAL archive on Postgres replica master servers after 7 days.

Ref issue #176

### CODE REVIEW

**Comment by jpmckinney** [comment]
Should `pg_archivecleanup` be used instead? https://www.percona.com/blog/2019/07/10/wal-retention-and-clean-up-pg_archivecleanup/

Here it is used from the replica: https://stackoverflow.com/a/16951547/244258 as mentioned here: https://www.postgresql.org/docs/12/warm-standby.html#STANDBY-SERVER-SETUP Here it is used by a shell script on the master, which is discouraged by some: https://stackoverflow.com/a/22965933/244258

On this page https://wiki.postgresql.org/wiki/Streaming_Replication and elsewhere, it's suggested to simply turn off archiving for streaming replication:

```
# Enable WAL archiving on the primary to an archive directory accessible from
# the standby. If wal_keep_segments is a high enough number to retain the WAL
# segments required for the standby server, this is not necessary.
```

So, perhaps the best option is to turn off archiving, and make sure `wal_keep_segments` is high enough?

**Comment by RobHooper** [comment]
I'd like to keep WAL archiving because it has already helped us restore the replica twice without requiring a full database dump / replica reset. 
We _shouldn't_ need it now that replica slots makes sure enough WAL segments are kept in `pg_wal`/`pg_xlog`. But I like having archiving as a fallback in case anything goes wrong.

As you've found `pg_archivecleanup` is a particularly good tool to clear down WAL files on replica servers, but the WAL archives are not proactively copied over so there isn't any need for it on there (copying archives to replica is something I considered and decided to not implement as mentioned on #176 ). 

We can use `pg_archivecleanup` to keep master in check but as these links mention, you still need a wrapper script to find and pass the correct arguments. We'd be swapping the script in my PR to run something like...
```find /var/lib/postgresql/11/main/archive/ -mtime +7 -printf '%f\n' | sort -r | head -1 | xargs pg_archivecleanup /var/lib/postgresql/11/main/archive/ ```
IMO this has the same results as the current proposed script so isn't worth doing. 


I think the discouragement you saw regarding this was around deleting files in `pg_wal`/`pg_xlog` and this is indeed bad as Postgres manages this directory. We are not doing this, instead we are looking to delete files from the `archive` directory which is a custom directory we've made and is only referred to in this [one config line](https://github.com/open-contracting/deploy/blob/868643da90a3f514ec7c12e135add821c4e93a06/salt/postgres/configs/kingfisher-process1-postgres.conf#L49).

**Comment by jpmckinney** [comment]
I'm fine with a 'belts-and-suspenders' approach. Can you add a comment in Salt explaining that:

> "Replica slots should make sure that enough WAL segments are kept in pg_wal/pg_xlog. 7 days of archives serves as a fallback in case anything goes wrong.

**Comment by RobHooper** [comment]
I've added these comments around maintaining the archive directory into the salt script.
I've also updated postgres.rst pointing to `recovery.conf` and adding some further docs around set up.

**Review by jpmckinney — APPROVED** [review]

**Comment by nutza249949** [comment]
thanks

**Pull request merged**
