### PR TITLE
Install certbot and a number of related improvements.

### PR DESCRIPTION
**Pull request by RobHooper**
@jpmckinney Apologies the below is a bit rambly, this PR isn't ready to merge yet but please can you have a look at it. 
I'm hoping you might be able to address some of the bugs I mention below. :smile: 

This PR replaces lets encrypt with certbot and makes a number of related improvements. 
Related issue #66

The version of certbot in the apt repos hasn't received reliable updates over the years so this PR uses the `snap` version instead. The certbot developers have said that they are making more of an effort to keep the snap version up to date. This is what we've been using on other systems.
Annoyingly snap support isn't in salt yet but it is coming down the line. I've put a comment in the code where this is relevant.

This PR also configures Apache to handle `.well-known` separately to sites. 
Currently a number of sites are unable to renew due to clashes with the site configuration and the certbot paths. This fixes them.
This is currently blocking the renewal of a number of domains so this part of the PR may need expediting.

Also, I've moved the SSL configuration into it's own file and generated a new "intermediate" list of ciphers. From here https://ssl-config.mozilla.org/
The original "intermediate" ciphers did support a greater number of browsers (https://www.ssllabs.com/ssltest/) so depending on the browsers you see visiting these apps we may want a looser cipher set.

This PR enables HTTP2 which is a nice win. 

When we deploy, we will need to run these additional tasks
* apt-get remove letsencrypt
* The Lets Encrypt configs have changed between versions and may need some manual intervention.

**I'm not happy with a few things about this PR**
Firstly, I've added a few files to `salt/apache/files` but that directory is getting messy with a number of things with different purposes. 
Perhaps shifting the site config includes into a new folder will help?

There is also a couple of bugs, firstly after loading in new Apache modules Apache needs restarting, currently it issues a reload but that isn't enough.

Secondly, when we're provisioning the SSL certs we need the Apache set up to be in a specific place.
We shouldn't put the site config in place before the certs are provisioned for it.
I expect this is happening in the current set up? 

Finally, in `libs.sls` `{{ servername }}_acquire_certs`, it should require that the `certbot` command is installed before running but I was struggling to get it working.
The normal `file: /snap/bin/certbot` errored for some reason.
Alternatively we could set a requirement for the certbot sls file but it wasn't as straight forward as I expected.

I really struggled to get my head around this part of the repo today. All of the Apache state files and config's feel too complex.

### CODE REVIEW

**Comment by jpmckinney** [comment]
@RobHooper Could you describe what seems too complex? There's a new documentation page that might help: https://ocdsdeploy.readthedocs.io/en/latest/develop/update/apache.html

* The idea for apache/modules is that not all services need all modules, so they can be individually loaded.
* `service` just sets up the service
* `htpasswd` just sets up htpasswd files
* `public` is the most common entry point from outside the state, and it includes `letsencrypt`

Last night I was looking at mod_md which seems even simpler than certbot. Can you have a look? https://www.cyberciti.biz/faq/how-to-secure-apache-with-mod_md-lets-encrypt-on-ubuntu-20-04-lts/

**Comment by jpmckinney** [comment]
That said, the SSL parts of complex, but only because we were going to replace them all as part of #66 :)

**Comment by jpmckinney** [comment]
> There is also a couple of bugs, firstly after loading in new Apache modules Apache needs restarting, currently it issues a reload but that isn't enough.

We can just remove `reload: true`. I don't think much is affected by a restart.

**Comment by jpmckinney** [comment]
> We can just remove reload: true. I don't think much is affected by a restart.

Done in acc64276cfae4710b4ede33bb1109c7b38bde777

I've also made some simplifications in 651559960af1156964c9a2e4d7f449c065634701

**Comment by jpmckinney** [comment]
> Firstly, I've added a few files to salt/apache/files but that directory is getting messy with a number of things with different purposes.
> Perhaps shifting the site config includes into a new folder will help?

I moved `.conf.include` files into `salt/apache/files/config` in c17f3416f6867d58329b356b133a31ba91929ca1

**Comment by jpmckinney** [comment]
> We could put service and htpasswd into init, but I thought single responsibility was simpler.

I put service into init in 651559960af1156964c9a2e4d7f449c065634701

**Comment by jpmckinney** [comment]
I'm part-way through implementing `mod_md`, and so far I've dropped to 2 state files and no new config files, so it's looking much simpler :)

**Comment by RobHooper** [comment]
@jpmckinney I do like the modular nature of it having the different parts of Apache in different files.

> Could you describe what seems too complex?

One thing I struggled with was working out how `_common.conf` worked. 
I can see the results from it running and they look good, it's just looking at the file it is a lot of Jinja templating. 
Personally, I would have created a couple of different template files for the different use cases (HTTP only, HTTPS with redirect)
I'm not sure if the listen to different ports functionality is needed / in use so we could possibly drop that.
Since we have `_common.conf` and it is working it isn't worth making this change just to make it easier to develop with.

I was hoping to set up a better default site along side these pull requests which is what lead me to digging this far into it.
URLs like this http://ocp02.open-contracting.org/, show the default Apache page which isn't a great look. No legitimate traffic should end up here, but just in case we recommend instead redirecting these somewhere else like www.open-contracting.org.
I think we can still do this by modifying `000-defaults.conf` - this should be it's own GH issue.

We do have a problem with terminology that adds to the confusion.
* "include" could refer to salt including other salt files, salt jinja including other files or apache including other files. 
* "config" just regarding Apache could mean either a global config (like the letsencrypt config in this commit or the ssl-intermidiate file)
I'm going to tweak my commit in a way I think will make this tidier. 

> We can just remove `reload: true`.

I can't think of an alternative so I'll make this change. Reload is nice for when when new sites are added/removed and other small config changes. 

> I put service into init
Awesome, I was going to suggest this change when I saw that `init.sls` was the only thing that referenced `service`.

> mod_md
I haven't come across `mod_md`, it looks interesting, I'll look more into it.

**Comment by jpmckinney** [comment]
@RobHooper Are you actively working on this now? If so, here's how far I got last night. I realized I needed to install a newer version of Apache; I was in the midst of adding a pkgrepo to apache/init.sls. I think the new version includes mod_md, which means not installing libapache2-mod-md in apache/modules/md.sls (which is only version 1.1.0 in Ubuntu 18.04).

```diff
diff --git a/docs/develop/commit.rst b/docs/develop/commit.rst
index 7918077..a70cb1c 100644
--- a/docs/develop/commit.rst
+++ b/docs/develop/commit.rst
@@ -59,7 +59,7 @@ Using a virtual machine
         VBoxManage guestproperty get VMNAME "/VirtualBox/GuestInfo/Net/0/V4/IP"
 
 #. Update the relevant target in ``salt-config/roster`` to point to the virtual machine's IP address
-#. In the relevant Pillar file, change ``https`` to ``no``, if certbot is used to enable HTTPS
+#. In the relevant Pillar file, change ``https`` to ``''``
 #. Edit ``/etc/hosts`` to map the virtual machine's IP address to the service's hostname
 #. Deploy to the virtual machine and test
 
@@ -70,7 +70,7 @@ Review code
 
 For context, for other repositories, work is done on a branch and tested on a local machine before a pull request is made, which is then tested on continuous integration, reviewed and approved before merging.
 
-However, for this repository, in some cases, it's impossible to test changes to server configurations, for example: if SSL certificates are involved (because certbot can't verify a virtual machine), or if external services are involved. In other cases, it's too much effort to setup a test environment in which to test changes.
+However, for this repository, in some cases, it's impossible to test changes to server configurations, for example: if SSL certificates are involved (because Let's Encrypt can't verify a virtual machine), or if external services are involved. In other cases, it's too much effort to setup a test environment in which to test changes.
 
 In such cases, the same process is followed as in other repositories, but without the benefit of tests.
 
diff --git a/docs/develop/update/apache.rst b/docs/develop/update/apache.rst
index 36ec115..3d3de0e 100644
--- a/docs/develop/update/apache.rst
+++ b/docs/develop/update/apache.rst
@@ -51,10 +51,8 @@ This will:
    -  Create a virtual host
    -  Set the ``servername`` and ``serveraliases``, if any
    -  Set up an HTTP/HTTPS redirect, if ``https`` is ``force``
-   -  Set up an `HTTP-01 challenge <https://letsencrypt.org/docs/challenge-types/>`__, if ``https`` is ``certonly``
 
 -  Symlink the new files from the ``etc/apache2/sites-enabled`` directory
--  Acquire SSL certificates if ``https`` is ``force`` or ``certonly``
 -  Restart the Apache service if the configuration changed
 
 The example above uses the `docs <https://github.com/open-contracting/deploy/blob/master/salt/apache/files/config/docs.conf.include>`__ configuration. The keys of the ``context`` mapping are made available as variables in the configuration template.
@@ -77,6 +75,8 @@ You might need to enable Apache modules to use non-core directives in your confi
 
 There are state files for common modules:
 
+apache.modules.md
+  Acquires `SSL certificates using Let's Encrypt <https://httpd.apache.org/docs/trunk/mod/mod_md.html>`__.
 apache.modules.proxy
   Adds `ProxyPass, ProxyPreserveHost and other directives <https://httpd.apache.org/docs/current/en/mod/mod_proxy.html>`__. Included by ``apache.modules.proxy_http`` and ``apache.modules.proxy_uwsgi``.
 apache.modules.proxy_http
@@ -86,7 +86,9 @@ apache.modules.proxy_uwsgi
 apache.modules.remoteip
   Adds `RemoteIPHeader, RemoteIPTrustedProxy and other directives <https://httpd.apache.org/docs/current/en/mod/mod_remoteip.html>`__.
 apache.modules.ssl
-  Adds `SSL directives <https://httpd.apache.org/docs/current/mod/mod_ssl.html>`__. Included by the ``apache.letsencrypt`` state file, which is included by the ``apache.public`` state file, which is included by the ``python_apps`` state file.
+  Included and required by ``apache.modules.md``.
+apache.modules.watchdog
+  Included and required by ``apache.modules.md``.
 
 To enable a module, include the relevant state file in your service's state file. For example:
 
diff --git a/docs/develop/update/index.rst b/docs/develop/update/index.rst
index f5e8573..65caa5d 100644
--- a/docs/develop/update/index.rst
+++ b/docs/develop/update/index.rst
@@ -189,5 +189,3 @@ Run, for example:
    ./run.py 'cove-ocds' file.remove /etc/apache2/sites-enabled/cove.conf
    ./run.py 'cove-ocds' file.remove /etc/apache2/sites-available/cove.conf
    ./run.py 'cove-ocds' file.remove /etc/apache2/sites-available/cove.conf.include
-
-You might also delete the SSL certificates like when :ref:`changing server name<change-server-name>`.
diff --git a/docs/develop/update/python.rst b/docs/develop/update/python.rst
index 73ca1af..e481621 100644
--- a/docs/develop/update/python.rst
+++ b/docs/develop/update/python.rst
@@ -12,9 +12,9 @@ If you already have an ``include`` state, add ``python_apps`` to its list.
 
 This will:
 
+-  Install the Apache service
 -  Install the uWSGI service
 -  Enable the :ref:`mod_proxy, mod_proxy_http and mod_proxy_uwsgi<apache-modules>` Apache modules
--  Restart the Apache service
 
 To make the Python app publicly accessible, :ref:`allow HTTP/HTTPS traffic<allow-http>`.
 
diff --git a/salt/apache/files/_common.conf b/salt/apache/files/_common.conf
index 6d5712b..ab72151 100644
--- a/salt/apache/files/_common.conf
+++ b/salt/apache/files/_common.conf
@@ -1,56 +1,28 @@
 # vi: ft=apache
+{#- https://github.com/icing/mod_md#readme #}
+{#- https://www.cyberciti.biz/faq/how-to-secure-apache-with-mod_md-lets-encrypt-on-ubuntu-20-04-lts/ #}
 
-# servername = {{ servername }}
-# serveraliases = {{ serveraliases }}
-# https = {{ https }}
-# ports = {{ ports }}
-
-{%- for port in ports %}
-    {%- if port not in (443, 80) %}
-Listen {{ port }}
+{%- if 443 in ports %}
+<MDomain {{ servername }}>
+    {%- if https == 'force' %}
+    MDRequireHttps temporary
     {%- endif %}
+</MDomain>
+{%- endif %}
 
-    {%- if port == 443 %}
-<IfModule mod_ssl.c>
-    {%- endif %}
-    <VirtualHost *:{{ port }}>
-        ServerName {{ servername }}
+{%- for port in ports %}
+<VirtualHost *:{{ port }}>
+    ServerName {{ servername }}
     {%- for serveralias in serveraliases %}
-        ServerAlias {{ serveralias }}
+    ServerAlias {{ serveralias }}
     {%- endfor %}
 
-    {%- if port == 80 and https == 'force' %}
-        Redirect / https://{{ servername }}/
-    {%- elif port == 80 and https == 'certonly' %}
-        # https://build.opensuse.org/package/view_file/security:dehydrated/dehydrated/acme-challenge.conf.apache.in
-        Alias /.well-known/acme-challenge/ /var/www/html/.well-known/acme-challenge/
-
-        <Directory "/var/www/html/.well-known/acme-challenge/">
-            Options None
-            AllowOverride None
-            Require all granted
-            ForceType text/plain
-        </Directory>
-    {%- else %}
-        {%- if port == 443 %}
-        SSLEngine on
-
-        # "Intermediate" configuration
-        SSLProtocol             all -SSLv2 -SSLv3
-        SSLCipherSuite          ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
-        SSLHonorCipherOrder     on
-        SSLCompression          off
-        SSLOptions +StrictRequire
-
-        SSLCertificateFile      /etc/letsencrypt/live/{{ servername }}/cert.pem
-        SSLCertificateKeyFile   /etc/letsencrypt/live/{{ servername }}/privkey.pem
-        SSLCertificateChainFile /etc/letsencrypt/live/{{ servername }}/chain.pem
-        {%- endif %}
-
-        Include {{ includefile }}
-    {%- endif %}
-    </VirtualHost>
     {%- if port == 443 %}
-</IfModule>
+    SSLEngine on
+    {%- endif %}
+
+    {%- if port == 443 or https != 'force' %}
+    Include {{ includefile }}
     {%- endif %}
+</VirtualHost>
 {%- endfor %}
diff --git a/salt/apache/files/config/000-default.conf.include b/salt/apache/files/config/000-default.conf.include
deleted file mode 100644
index 44de6b9..0000000
--- a/salt/apache/files/config/000-default.conf.include
+++ /dev/null
@@ -1,6 +0,0 @@
-# vi: ft=apache
-
-DocumentRoot /var/www/html
-
-ErrorLog ${APACHE_LOG_DIR}/error.log
-CustomLog ${APACHE_LOG_DIR}/access.log combined
diff --git a/salt/apache/init.sls b/salt/apache/init.sls
index 7d9bdfa..f757958 100644
--- a/salt/apache/init.sls
+++ b/salt/apache/init.sls
@@ -9,6 +9,8 @@
 {% endif %}
 
 apache2:
+  pkgrepo.managed:
+    - ppa: ondrej/apache2
   pkg.installed:
     - name: apache2
   service.running:
@@ -17,6 +19,20 @@ apache2:
     - require:
       - pkg: apache2
 
+/etc/apache2/conf-available/letsencrypt.conf:
+  file.managed:
+    - source: salt://apache/files/letsencrypt.conf
+    - watch_in:
+      - service: apache2
+
+/etc/apache2/conf-enabled/letsencrypt.conf:
+  file.symlink:
+    - target: /etc/apache2/conf-available/letsencrypt.conf
+    - require:
+      - file: /etc/apache2/conf-available/letsencrypt.conf
+    - watch_in:
+      - service: apache2
+
 {% if salt['pillar.get']('apache:sites') %}
 {% for name, entry in pillar.apache.sites.items() %}
 {{ apache(name, entry) }}
diff --git a/salt/apache/letsencrypt.sls b/salt/apache/letsencrypt.sls
deleted file mode 100644
index 4286ff0..0000000
--- a/salt/apache/letsencrypt.sls
+++ /dev/null
@@ -1,21 +0,0 @@
-include:
-  - apache.modules.ssl
-
-/var/www/html/.well-known/acme-challenge:
-  file.directory:
-    - user: www-data
-    - group: www-data
-    - makedirs: True
-
-letsencrypt:
-  pkg.installed
-
-cron-letsencrypt-renew:
-  cron.present:
-    - identifier: letsencrypt-renew
-    - name: letsencrypt renew --no-self-upgrade >/dev/null 2>&1
-    - user: root
-    - minute: random
-    - hour: 7
-  require:
-    - pkg: letsencrypt
diff --git a/salt/apache/modules/md.sls b/salt/apache/modules/md.sls
new file mode 100644
index 0000000..396983f
--- /dev/null
+++ b/salt/apache/modules/md.sls
@@ -0,0 +1,13 @@
+include:
+  - apache
+  - apache.modules.ssl
+  - apache.modules.watchdog
+
+md:
+  pkg.installed:
+    - name: libapache2-mod-md
+  apache_module.enabled:
+    - require:
+      - pkg: md
+    - watch_in:
+      - service: apache2
diff --git a/salt/apache/modules/watchdog.sls b/salt/apache/modules/watchdog.sls
new file mode 100644
index 0000000..a49f299
--- /dev/null
+++ b/salt/apache/modules/watchdog.sls
@@ -0,0 +1,7 @@
+include:
+  - apache
+
+watchdog:
+  apache_module.enabled:
+    - watch_in:
+      - service: apache2
diff --git a/salt/apache/public.sls b/salt/apache/public.sls
deleted file mode 100644
index 82a09a2..0000000
--- a/salt/apache/public.sls
+++ /dev/null
@@ -1,8 +0,0 @@
-{% from 'lib.sls' import apache %}
-
-include:
-  - apache.letsencrypt
-
-# https://github.com/OpenDataServices/opendataservices-deploy/commit/34f093188b9d0d58fc2bed76643b22afa3b9ff83
-# https://github.com/open-contracting/deploy/issues/19
-{{ apache('000-default', {'configuration': '000-default', 'servername': grains.fqdn}) }}
diff --git a/salt/lib.sls b/salt/lib.sls
index b929e04..aa39445 100644
--- a/salt/lib.sls
+++ b/salt/lib.sls
@@ -41,19 +41,24 @@ unset {{ setting_name }} firewall setting:
 {% endmacro %}
 
 
+{#
+  Accepts a `name` string used to name configuration files, an `entry` object with Apache configuration, and a
+  `context` object, whose keys are made available as variables in the configuration template.
+
+  See https://ocdsdeploy.readthedocs.io/en/latest/develop/update/apache.html
+#}
 # It is safe to use `{}` as a default value, because the default value is never mutated.
 {% macro apache(name, entry, context={}) %}
 
-{% set https = entry.get('https', '') %}
-{% set serveraliases = entry.get('serveraliases', []) %}
-
 {% if not context %}
   {% set context = entry.get('context', {}) %}
 {% endif %}
 
+{% set serveraliases = entry.get('serveraliases', []) %}
+{% set https = entry.get('https', '') %}
 {% if https == 'force' %}
   {% set ports = [80, 443] %}
-{% else %} {# https == 'certonly', used to serve /.well-known/acme-challenge over HTTP, or turned off #}
+{% else %} {# https = '' #}
   {% set ports = [80] %}
 {% endif %}
 
@@ -82,29 +87,6 @@ unset {{ setting_name }} firewall setting:
     - watch_in:
       - service: apache2
 
-{% if https == 'force' or https == 'certonly' %}
-
-{% set domainargs = "-d " + " -d ".join([entry.servername] + serveraliases) %}
-
-{{ entry.servername }}_acquire_certs:
-  cmd.run:
-    - name: /etc/init.d/apache2 reload; letsencrypt certonly --non-interactive --no-self-upgrade --expand --email sysadmin@open-contracting.org --agree-tos --webroot --webroot-path /var/www/html/ {{ domainargs }}
-    - creates:
-      - /etc/letsencrypt/live/{{ entry.servername }}/cert.pem
-      - /etc/letsencrypt/live/{{ entry.servername }}/chain.pem
-      - /etc/letsencrypt/live/{{ entry.servername }}/fullchain.pem
-      - /etc/letsencrypt/live/{{ entry.servername }}/privkey.pem
-    - require:
-      - pkg: letsencrypt
-      - file: /etc/apache2/sites-available/{{ name }}.conf
-      - file: /etc/apache2/sites-available/{{ name }}.conf.include
-      - file: /etc/apache2/sites-enabled/{{ name }}.conf
-      - file: /var/www/html/.well-known/acme-challenge
-    - watch_in:
-      - service: apache2
-
-{% endif %}
-
 /etc/apache2/sites-enabled/{{ name }}.conf:
   file.symlink:
     - target: /etc/apache2/sites-available/{{ name }}.conf
@@ -120,10 +102,11 @@ unset {{ setting_name }} firewall setting:
 {#
   Accepts a `name` parameter, which must match the repository name of a Prometheus component: for example, prometheus.
 
-  The macro reads Pillar data from the `prometheus.{name}` key. The variables below refer to keys in this Pillar data.
+  The macro reads Pillar data from the `prometheus.{name}` key. The backticks below refer to keys in this Pillar data.
 
   The macro creates states to:
 
+  - Create a `user`
   - Download and extract the specified `version` of the named component to the `user`'s home directory
   - Create `config`uration files in the user's home directory, if any
   - Create a systemd `service` file from a `salt/prometheus/files/systemd/{service}.service` template,
diff --git a/salt/python_apps.sls b/salt/python_apps.sls
index 4f21319..3fde299 100644
--- a/salt/python_apps.sls
+++ b/salt/python_apps.sls
@@ -4,7 +4,7 @@
 # add boolean key to the Pillar data to indicate whether to include these.
 include:
   - uwsgi
-  - apache.public
+  - apache
   - apache.modules.proxy_http
   - apache.modules.proxy_uwsgi
 
diff --git a/salt/top.sls b/salt/top.sls
index c8d3adc..a8bdbd3 100644
--- a/salt/top.sls
+++ b/salt/top.sls
@@ -56,7 +56,7 @@ base:
     - apache.htpasswd
 
   'I@apache:sites':
-    - apache.public
+    - apache
     # So far, all servers with sites configure a reverse proxy.
     - apache.modules.proxy_http
 
```

**Comment by RobHooper** [comment]
@jpmckinney I've just been testing mod_md manually nothing in salt yet. 
Happy to pick this up or for you to keep developing the `mod_md` side of things, I need to focus on a couple of other tasks first so you may be able to do this quicker. :)

I've just committed a few changes that shift things into what I feel are better, more descriptive directory names + updating macros to reflect them.

**Comment by jpmckinney** [comment]
@RobHooper Sounds good. I'll cherry-pick or otherwise copy your changes, and do a `mod_md` test later today.

**Comment by jpmckinney** [comment]
> One thing I struggled with was working out how _common.conf worked.
> I can see the results from it running and they look good, it's just looking at the file it is a lot of Jinja templating.

The file is much shorter now and easier to read :) https://github.com/open-contracting/deploy/blob/master/salt/apache/files/_common.conf

> I'm not sure if the listen to different ports functionality is needed / in use so we could possibly drop that.

Removed.

> I was hoping to set up a better default site along side these pull requests which is what lead me to digging this far into it.

Please create a GitHub issue. I think ODS added a default virtual host, because otherwise, as I understand, requests for http://ocpXX.open-contracting.org get served by the other virtual host – but Django apps set `ALLOWED_HOSTS` and are configured to ignore errors from denied hosts, and most non-Django apps have basic authentication, so this might not be much of a concern. In any case, I don't know what the best practice is. For now, I removed any default host from Salt.

> "include" could refer to salt including other salt files, salt jinja including other files or apache including other files.
> "config" just regarding Apache could mean either a global config (like the letsencrypt config in this commit or the ssl-intermidiate file)

I'll take your same idea and name the folders `conf/` and `sites/` to correspond to `conf-available` and `sites-available`.

> > We can just remove reload: true.
>
> I can't think of an alternative so I'll make this change. Reload is nice for when when new sites are added/removed and other small config changes.

I think I found a solution using `module.wait` with `service.reload`: https://github.com/open-contracting/deploy/blob/master/salt/apache/init.sls

I'll close this PR as I've taken (or will take) the bits into master, which uses mod_md now.

**Pull request closed without merging**
