### PR TITLE
kingfisher: Add Postgres Specific settings

### PR DESCRIPTION
**Pull request by odscjames**
https://github.com/open-contracting/deploy/issues/144

### CODE REVIEW

**Comment by odscjames** [comment]
[Kingfisher: Changes to postgresql.conf are not in Salt](https://trello.com/c/ssC6B4tA/222-kingfisher-changes-to-postgresqlconf-are-not-in-salt)

**Comment by odscjames** [comment]
Prepared pull request as requested in https://github.com/open-contracting/deploy/issues/144

The plan is when we deploy this, we set postgresql.conf back to the original by hand - see issue for a copy.

I note the following problems with the current Salt / this P.R.:

- salt/postgres11.sls file has a file name that suggest it is for any postgres server but it already has kingfisher specific stuff in it. So I continued by adding stuff here.
- salt/postgres11.sls file prob has sequence errors on first install - It might add /etc/postgresql/11/main/pg_hba.conf first then install the package and the package might alter it? 
- salt/postgres11.sls does not restart server if it's config files change ...
- .... but that is complex, because if the postgres server might restart we need to make sure all the tasks in salt/ocdskingfisherprocess.sls that do database things will happen after the restart (or before, just not during. After probably makes sense.) Also, you need to give the postgres server some time to restart after issuing the command before trying to do DB actions or it might not be ready yet.  

In the interests of clearing up a bad situation on the server, unblocking other work that I understand relies on this and as the current Salt has these issues anyway, I'll put this forwards for consideration now and suggest we turn those things into issues afterwards - but open to discussion, of course.

**Comment by odscjames** [comment]
Also note the end result of this should be that no setting actually changes on the DB server - it just makes what is there managed by salt. In the issue I've commented on some things we might want to change but again lets do those later.

**Comment by jpmckinney** [comment]
Thanks, @odscjames. @dogsbody @RobHooper: I'll be away next week, but I'm happy for you to take this forward in your work on setting up a replica.

**Comment by RobHooper** [comment]
@odscjames I'm happy the postgres configuration changes - in the sense that this commits what is currently configured on the server. (I haven't double checked the values themselves as I plan to do further performance tuning later down the line.)

I agree with the problems you identified, as part of the postgres-replica build I've been refactoring the postgres11.sls file so a fix is inbound. 

One fix I've pulled forward here is to restart postgres after config changes. I think this is needed to address a couple of risks:
- Reducing the chance of the "active" postgres configuration and the one in salt becoming out of sync 
- A broken config being deployed and not realised until something else restarted the service

The second change is renaming the config file, this is what my refactored code will be using so it will make the implementation of that easier.

**Comment by Bjwebb** [comment]
I'm taking over Open Data Services' Kingfisher dev work from @odscjames for a few weeks.

Those changes look good. I think we're ready to merge and deploy this pull request. @RobHooper, do you want to do that, or shall I?

**Comment by RobHooper** [comment]
I agree, ready to merge and deploy. Happy for either of us to do this.

**Comment by Bjwebb** [comment]
Would be great if you could do it.

**Comment by RobHooper** [comment]
:+1: I'll merge and deploy this tomorrow morning (UK Time)

**Comment by Bjwebb** [comment]
Looks like this didn't get deployed? Are you able to pick this up next week?

**Comment by RobHooper** [comment]
Sorry for the delay Ben, I tried to deploy twice and was blocked by people using Kingfisher. Deployed now.

**Comment by Bjwebb** [comment]
Thanks, makes sense.

**Pull request merged**
