### PR TITLE
Change Kingfisher Process host to OCP domain

### PR DESCRIPTION
**Pull request by jpmckinney**
I'll also have to update the UptimeRobot monitor: https://uptimerobot.com/dashboard#783273034

### CODE REVIEW

**Comment by odscjames** [comment]
This had weird problems: https://github.com/open-contracting/kingfisher-process/issues/158

**Comment by jpmckinney** [comment]
In the linked issue, only the apache config had changed (ServerAlias). Wouldn't the pillar file have to change (in any case, it couldn't hurt)?

I'm not sure that the hyphen is the issue – it seems like it's a red herring.

I notice that both `ocdskingfisherprocess.sls` and `ocdskingfisherpscrape.sls` use the same servername (`ocdskingfisher-dev`) for the `apache` macro. Wouldn't this produce two VirtualHost's with the same ServerName, which was the problem in the first StackOverflow issue?

**Comment by odscjames** [comment]
> In the linked issue, only the Apache config had changed (ServerAlias). Wouldn't the pillar file also have to change as in this PR (in any case, it couldn't hurt)?

We need to do both: we need to add the ServerAlias line and make sure it works so Apache will accept the request correctly. Only then can we change the pillar variable as this pull request does. Changing the pillar request before we get Apache working properly will result in a broken system.

 > I notice that both ocdskingfisherprocess.sls and ocdskingfisherpscrape.sls use the same servername (ocdskingfisher-dev) for the apache macro. Wouldn't this produce two VirtualHost's with the same ServerName, which was the problem in the first StackOverflow issue?

I don't think that's quite the solution S.O. link had but good catch - we do. We should at least clean that up and see if that helps. I will try and do that soon.

**Comment by odscjames** [comment]
[Serve API and web app from process.kingfisher.open-contracting.org](https://trello.com/c/aIgP4fhz/40-serve-api-and-web-app-from-processkingfisheropen-contractingorg)

**Comment by odscjames** [comment]
> We should at least clean that up 

Done. Will  report more on https://github.com/open-contracting/kingfisher-process/issues/158

**Comment by jpmckinney** [comment]
Closing in favor of open-contracting/kingfisher-process#158

**Pull request closed without merging**
